### ISSUE TITLE
Continuous Integration Addition

### ISSUE THREAD

**Issue by Liang-Hsuan** [Kicks4Love/kicks4love#45]
To further prevent building more technical debt and save more time for developer using automation, CI should be added for the project.

Some choices for CI tools:

- CircleCI
- Travis

**Let's go DevOps**

![DevOps](https://cdn-images-1.medium.com/max/2000/1*EBXc9eJ1YRFLtkNI_djaAw.png)

**Comment by leonma333** [comment]
Fixed in #48
